<?php

namespace App\Services\Seo;

/**
 * Builds the robots.txt body for whichever host this installation answers as.
 *
 * The policy is deliberately fail-closed. `seo.robots.public_hosts` is an
 * allow-list, so a staging box, a preview URL, a developer's Herd domain and a
 * production host with a typo in APP_URL all receive `Disallow: /`. Getting
 * `Disallow: /` on a host that should have been public is a visible,
 * recoverable mistake; the opposite is a staging site in the index.
 */
class RobotsTxt
{
    public const POLICY_OPEN = 'open';

    public const POLICY_CLOSED = 'closed';

    public function __construct(private readonly PublicUrls $urls) {}

    /**
     * The robots.txt body, terminated by a newline.
     */
    public function body(): string
    {
        return $this->policy() === self::POLICY_OPEN
            ? $this->openBody()
            : $this->closedBody();
    }

    /**
     * Which policy this host resolves to.
     */
    public function policy(): string
    {
        return $this->isPublicHost() ? self::POLICY_OPEN : self::POLICY_CLOSED;
    }

    /**
     * Whether `app.url`'s host is on the allow-list.
     */
    public function isPublicHost(): bool
    {
        $host = $this->host();

        if ($host === null) {
            return false;
        }

        /** @var array<int, string> $public */
        $public = config('seo.robots.public_hosts', []);

        return in_array($host, array_map('strtolower', $public), true);
    }

    /**
     * The host `app.url` points at, lowercased, or null if it has none.
     *
     * Reads the config directly rather than through PublicUrls::baseUrl(),
     * which throws on a blank APP_URL. Throwing is right for a canonical URL —
     * a wrong one is worse than none — but robots.txt must never 500: a
     * missing host is exactly the case the closed policy exists to serve.
     */
    public function host(): ?string
    {
        $host = parse_url((string) config('app.url', ''), PHP_URL_HOST);

        return is_string($host) && $host !== '' ? strtolower($host) : null;
    }

    /**
     * @return array<int, string>
     */
    protected function disallowedPaths(): array
    {
        /** @var array<int, string> $paths */
        $paths = config('seo.robots.disallow', []);

        return $paths;
    }

    protected function openBody(): string
    {
        $lines = [
            $this->header(),
            '',
            'User-agent: *',
        ];

        foreach ($this->disallowedPaths() as $path) {
            $lines[] = 'Disallow: '.$path;
        }

        /** @var array<int, string> $training */
        $training = config('seo.robots.ai_crawlers.training', []);

        if ($training !== []) {
            $lines[] = '';
            $lines[] = '# Training-corpus crawlers: the site is not a training corpus.';

            foreach ($training as $agent) {
                $lines[] = '';
                $lines[] = 'User-agent: '.$agent;
                $lines[] = 'Disallow: /';
            }
        }

        /** @var array<int, string> $answer */
        $answer = config('seo.robots.ai_crawlers.answer', []);

        if ($answer !== []) {
            $lines[] = '';
            $lines[] = '# Answer and search crawlers: same rules as any other crawler.';
            $lines[] = '';

            foreach ($answer as $agent) {
                $lines[] = 'User-agent: '.$agent;
            }

            foreach ($this->disallowedPaths() as $path) {
                $lines[] = 'Disallow: '.$path;
            }
        }

        $lines[] = '';
        $lines[] = 'Sitemap: '.$this->urls->baseUrl().'/sitemap.xml';

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    protected function closedBody(): string
    {
        return implode(PHP_EOL, [
            $this->header(),
            '# '.($this->host() ?? 'This host').' is not a public Workumi host, so indexing is disabled.',
            '',
            'User-agent: *',
            'Disallow: /',
        ]).PHP_EOL;
    }

    protected function header(): string
    {
        return '# Generated by `php artisan seo:publish-robots`. Edit config/seo.php, not this file.';
    }
}
